INSERT INTO artist (name, genre, top_song) VALUES ( 'Adele', 'Pop, Soul', 'Hello' );
INSERT INTO artist (name, genre, top_song) VALUES ('Beyonce', 'Pop, R&B', 'Crazy In Love');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Taylor Swift', 'Pop, Country', 'Shake It Off');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Ed Sheeren', 'Pop, Folk', 'Shape Of You');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Bruno Mars', 'Pop, R&B', 'Uptown Funk');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Lady Gaga', 'Pop', 'Bad Romance');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Rihanna', 'Pop, R&B', 'Umbrella');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Justin Bieber', 'Pop, R&B', 'Sorry');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Drake', 'Hip Hop, Rap', 'Hotline Bling');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Katy Perry', 'Pop', 'Roar');
INSERT INTO artist (name, genre, top_song) VALUES ( 'The Weeknd', 'R&B, Pop', 'Blinding Lights');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Elton John', 'Rock, Pop', 'Rocket Man');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Billie Eilish', 'Pop, Alternative', 'Bad Guy');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Sam Smith', 'Pop, Soul', 'Stay With Me');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Sia', 'Pop', 'Chandelier');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Post Malone', 'Hip Hop, Pop, Country', 'Circles');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Shawn Mendes', 'Pop', 'Stiches');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Dua Lipa', 'Pop', 'Dont Start Now');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Mariah Carey', 'Pop, R&B','We Belong Together');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Whitney Houston', 'Pop, R&B', 'I Will Always Love You');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Celine Dion', 'Pop', 'My Heart Will Go On');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Alicia keys', 'R&B, Soul', 'If I Aint Got You');
INSERT INTO artist (name, genre, top_song) VALUES ( 'John Legend', 'R&B, Soul', 'All Of Me');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Pink', 'Pop, Rock', 'Just Give Me a Reason');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Usher', 'R&B, Pop', 'Yeah!');
INSERT INTO artist (name, genre, top_song) VALUES ( 'SZA', 'R&B', 'Good Days');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Amy Winehouse', 'Soul, Jazz', 'Rehab');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Gwen Stefani', 'Pop', 'Hollaback Girl');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Carrie Underwood', 'Country', 'Before He Cheats');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Chappell Roan', 'Pop', 'Pink Pony Club');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Brenton Wood', 'R&B, Soul', 'Gimme Little Sign');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Smokey Robinson', 'R&B, Soul','Cruisin' );
INSERT INTO artist (name, genre, top_song) VALUES ( 'Luke Combs', 'Country', 'Beatiful Crazy');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Morgan Wallen', 'Country', 'Whiskey Glasses');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Jason Aldean', 'Country', 'Dirt Road Anthem');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Karol G', 'Latin', 'Tusa');
INSERT INTO artist (name, genre, top_song) VALUES ( 'The Beatles', 'Rock, Pop', 'Hey Jude');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Elvis Presley', 'Rock, Pop', 'Suspicious Minds');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Madonna', 'Pop', 'Like a Virgin');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Frank Sinatra', 'Jazz, Swing', 'My Way');
INSERT INTO artist (name, genre, top_song) VALUES ( 'James Brown', 'Funk, Soul', 'I Got You');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Stevie Wonder', 'R&B, Soul', 'Superstition');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Selena', 'Tejano, Latin', 'Bidi Bidi Bom Bom');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Prince', 'Pop, Funk', 'Purple Rain');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Queen', 'Rock', 'Bohemian Rhapsody');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Hank Williams', 'Country', 'Your Cheatin Heart');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Diana Ross', 'R&B, Pop', 'Aint No Mountain High Enough');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Johnny Cash', 'Country, Rock', 'Ring of Fire');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Shakira', 'Pop, Latin', 'Hips Dont Lie');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Vicente Fernandez', 'Ranchera, Mariachi', 'El Rey');
INSERT INTO artist (name, genre, top_song) VALUES ( 'Sam Cooke', 'Soul,R&B', 'A Change Is Gonna Come');


