spring:
  datasource: 
    username: music_streamer
    password: music_streamer
    url: jdbc:mysql://localhost:3306/music_streamer
    
  jpa: 
    hibernate:
      ddl-auto: none
    show-sql: true
 
  sql:
    init:
      mode: never